services:
  - type: web
    name: nforcehq-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: FLYWAY_DB_USER
        sync: false
      - key: FLYWAY_DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
