services:
  - type: web
    name: nforcehq-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/nforcehq-0.0.1-SNAPSHOT.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: FLYWAY_DB_USER
        sync: false
      - key: FLYWAY_DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
